-- CHANGE THIS
SET @DATE_START = '2013-04-11'; 
-- CHANGE THIS

SET SQL_SAFE_UPDATES=0; 

DROP TABLE IF EXISTS TMP_ONLINE_USERS;
CREATE TABLE TMP_ONLINE_USERS ( 
    id INT NOT NULL AUTO_INCREMENT,
    date DATETIME NULL,
    onlineCount INT NULL,
    PRIMARY KEY ( id )
 );

INSERT INTO TMP_ONLINE_USERS (date, onlineCount) SELECT  DATE_FORMAT(s.timeStamp,'%Y-%m-%d %H:%i'), COUNT(DISTINCT(sessionId))
FROM TRACKER_CONNECTION_STATISTICS s
WHERE  timeStamp >= "2013-04-11"
AND ticksPerSecond > 0
GROUP BY DATE_FORMAT(s.timeStamp,'%d-%m-%Y %H:%i');

SELECT CONCAT(DATE_FORMAT(date,'%d.%m.%Y %H'),':00'), FORMAT(SUM(onlineCount) / 60, 0) 
  FROM TMP_ONLINE_USERS s
  GROUP BY DATE_FORMAT(date,'%d.%m.%Y %H')
  ORDER BY date ASC;

SET SQL_SAFE_UPDATES=1;