
SET SQL_SAFE_UPDATES=0; 

ALTER TABLE TERRAIN_SURFACE_IMAGE CHANGE COLUMN surfaceType surfaceTypeTMP INT(11) NULL DEFAULT NULL ;
ALTER TABLE TERRAIN_SURFACE_IMAGE ADD surfaceType VARCHAR(255) AFTER surfaceTypeTMP;
UPDATE TERRAIN_SURFACE_IMAGE SET surfaceType = 'NONE' WHERE surfaceTypeTMP = 0;
UPDATE TERRAIN_SURFACE_IMAGE SET surfaceType = 'WATER' WHERE surfaceTypeTMP = 1;
UPDATE TERRAIN_SURFACE_IMAGE SET surfaceType = 'LAND' WHERE surfaceTypeTMP = 2;
UPDATE TERRAIN_SURFACE_IMAGE SET surfaceType = 'COAST' WHERE surfaceTypeTMP = 3;
UPDATE TERRAIN_SURFACE_IMAGE SET surfaceType = 'COAST' WHERE surfaceTypeTMP = 4;
ALTER TABLE TERRAIN_SURFACE_IMAGE DROP COLUMN surfaceTypeTMP;

ALTER TABLE TERRAIN_IMAGE_TILE_SURFACE_TYPE CHANGE COLUMN surfaceType surfaceTypeTMP INT(11) NULL DEFAULT NULL ;
ALTER TABLE TERRAIN_IMAGE_TILE_SURFACE_TYPE ADD surfaceType VARCHAR(255) AFTER surfaceTypeTMP;
UPDATE TERRAIN_IMAGE_TILE_SURFACE_TYPE SET surfaceType = 'NONE' WHERE surfaceTypeTMP = 0;
UPDATE TERRAIN_IMAGE_TILE_SURFACE_TYPE SET surfaceType = 'WATER' WHERE surfaceTypeTMP = 1;
UPDATE TERRAIN_IMAGE_TILE_SURFACE_TYPE SET surfaceType = 'LAND' WHERE surfaceTypeTMP = 2;
UPDATE TERRAIN_IMAGE_TILE_SURFACE_TYPE SET surfaceType = 'COAST' WHERE surfaceTypeTMP = 3;
UPDATE TERRAIN_IMAGE_TILE_SURFACE_TYPE SET surfaceType = 'COAST' WHERE surfaceTypeTMP = 4;
ALTER TABLE TERRAIN_IMAGE_TILE_SURFACE_TYPE DROP COLUMN surfaceTypeTMP;

ALTER TABLE TERRAIN_IMAGE_GROUP CHANGE COLUMN `htmlBackgroundColorLandCoast` `htmlBackgroundColorCoast`  VARCHAR(255) NULL DEFAULT NULL ;
UPDATE TERRAIN_IMAGE_GROUP SET htmlBackgroundColorCoast = htmlBackgroundColorWaterCoast WHERE htmlBackgroundColorWaterCoast IS NOT NULL;
ALTER TABLE TERRAIN_IMAGE_GROUP DROP COLUMN htmlBackgroundColorWaterCoast;

ALTER TABLE ITEM_TYPE CHANGE COLUMN terrainType terrainTypeTMP INT(11) NULL DEFAULT NULL ;
ALTER TABLE ITEM_TYPE ADD terrainType VARCHAR(255) AFTER terrainTypeTMP;
UPDATE ITEM_TYPE SET terrainType = 'LAND' WHERE terrainTypeTMP = 0;
UPDATE ITEM_TYPE SET terrainType = 'WATER' WHERE terrainTypeTMP = 1;
UPDATE ITEM_TYPE SET terrainType = 'LAND_COAST' WHERE terrainTypeTMP = 3;
UPDATE ITEM_TYPE SET terrainType = 'WATER_COAST' WHERE terrainTypeTMP = 4;
ALTER TABLE ITEM_TYPE DROP COLUMN terrainTypeTMP;

SET SQL_SAFE_UPDATES=1;