SET SQL_SAFE_UPDATES=0;

ALTER TABLE GUIDANCE_LEVEL ADD COLUMN number INT(11) NULL DEFAULT NULL AFTER id;
ALTER TABLE GUIDANCE_LEVEL ADD COLUMN xp INT(11) NULL DEFAULT NULL AFTER maxMoney;

UPDATE GUIDANCE_LEVEL SET name = 999 WHERE name = "NIRVANA";
UPDATE GUIDANCE_LEVEL SET number = name;
ALTER TABLE GUIDANCE_LEVEL DROP COLUMN name;

UPDATE GUIDANCE_LEVEL l SET l.xp = (SELECT p.theCount 
  FROM GUIDANCE_COMPARISON p, GUIDANCE_CONDITION_CONFIG c 
  WHERE 
    l.dbConditionConfig_id = c.id 
    AND c.dbAbstractComparisonConfig_id = p.id);
UPDATE GUIDANCE_LEVEL SET xp = 99999999 WHERE id = 74;
ALTER TABLE GUIDANCE_LEVEL DROP FOREIGN KEY FKE053FFBD76CA87AE;
ALTER TABLE GUIDANCE_LEVEL DROP INDEX FKE053FFBD76CA87AE;
DELETE FROM GUIDANCE_CONDITION_CONFIG WHERE id IN (SELECT dbConditionConfig_id FROM GUIDANCE_LEVEL);
DELETE FROM GUIDANCE_COMPARISON WHERE id NOT IN (SELECT dbAbstractComparisonConfig_id FROM GUIDANCE_CONDITION_CONFIG);
ALTER TABLE GUIDANCE_LEVEL DROP COLUMN dbConditionConfig_id;

SET SQL_SAFE_UPDATES=1;
