DROP TABLE IF EXISTS BACKUP_USER_ITEM_TYPE_ACCESS_BOUGHT;
DROP TABLE IF EXISTS BACKUP_LEVEL_COMPARISON_SYNC_ITEM_TYPE;
DROP TABLE IF EXISTS BACKUP_GENERIC_ITEM;
ALTER TABLE `gamedb`.`BACKUP_LEVEL_COMPARISON` DROP INDEX `FKE4D6B8A1A6F945EA`, DROP FOREIGN KEY `FKE4D6B8A1A6F945EA`;
DROP TABLE IF EXISTS BACKUP_USER_STATUS;
DROP TABLE IF EXISTS BACKUP_LEVEL_COMPARISON;
DROP TABLE IF EXISTS BACKUP_USER_ITEM_TYPE_ACCESS;
DROP TABLE IF EXISTS BACKUP_BASE;
DROP TABLE IF EXISTS BACKUP_ENTRY;
