CREATE TABLE TERRAIN_SETTINGS (
    id INTEGER NOT NULL IDENTITY PRIMARY KEY,
    tileHeight INTEGER NOT NULL,
    tileWidth INTEGER NOT NULL,
    tileXCount INTEGER NOT NULL,
    tileYCount INTEGER NOT NULL,
    name VARCHAR(255),
    isRealGame INTEGER DEFAULT NULL
);

CREATE TABLE TERRAIN_IMAGE (
    id INTEGER NOT NULL IDENTITY PRIMARY KEY,
    contentType VARCHAR(255) DEFAULT NULL,
    imageData BINARY,
    tileHeight INTEGER NOT NULL,
    tileWidth INTEGER NOT NULL
);

CREATE TABLE  TERRAIN_IMAGE_TILE_SURFACE_TYPE (
    id INTEGER NOT NULL IDENTITY PRIMARY KEY,
    surfaceType INTEGER NOT NULL,
    tileX INTEGER NOT NULL,
    tileY INTEGER NOT NULL,
    dbTerrainImage_id INTEGER NOT NULL
);
ALTER TABLE TERRAIN_IMAGE_TILE_SURFACE_TYPE ADD CONSTRAINT FK_TERRAIN_IMAGE_TILE_SURFACE_TYPE_TERRAIN_SETTINGS FOREIGN KEY (dbTerrainImage_id) REFERENCES TERRAIN_IMAGE(id);

CREATE TABLE  TERRAIN_SURFACE_IMAGE (
    id INTEGER NOT NULL IDENTITY PRIMARY KEY,
    contentType VARCHAR(255) DEFAULT NULL,
    imageData BINARY,
    surfaceType INTEGER NOT NULL
);

CREATE TABLE TERRAIN_IMAGE_POSITION (
    id INTEGER NOT NULL IDENTITY PRIMARY KEY,
    tileX INTEGER NOT NULL,
    tileY INTEGER NOT NULL,
    dbTerrainImage_id INTEGER DEFAULT NULL,
    dbTerrainSetting_id INTEGER NOT NULL,
    CONSTRAINT TERRAIN_TILE_CONSTRAINT UNIQUE (tileX, tileY, dbTerrainImage_id, dbTerrainSetting_id)
);
ALTER TABLE TERRAIN_IMAGE_POSITION ADD CONSTRAINT FK_TERRAIN_IMAGE_POSITION_TERRAIN_IMAGE FOREIGN KEY (dbTerrainImage_id) REFERENCES TERRAIN_IMAGE(id);
ALTER TABLE TERRAIN_IMAGE_POSITION ADD CONSTRAINT FK_TERRAIN_IMAGE_POSITION_TERRAIN_SETTINGS FOREIGN KEY (dbTerrainSetting_id) REFERENCES TERRAIN_SETTINGS(id);

CREATE TABLE TERRAIN_SURFACE_RECT (
    id INTEGER NOT NULL IDENTITY PRIMARY KEY,
    tileHeight INTEGER NOT NULL,
    tileWidth INTEGER NOT NULL,
    tileX INTEGER NOT NULL,
    tileY INTEGER NOT NULL,
    dbSurfaceImage_id INTEGER DEFAULT NULL,
    dbTerrainSetting_id INTEGER DEFAULT NULL,
    CONSTRAINT SURFACE_TILE_CONSTRAINT UNIQUE (tileX, tileY, tileWidth, tileHeight, dbSurfaceImage_id, dbTerrainSetting_id)
);
ALTER TABLE TERRAIN_SURFACE_RECT ADD CONSTRAINT FK_TERRAIN_SURFACE_RECT_TERRAIN_SURFACE_IMAGE FOREIGN KEY (dbSurfaceImage_id) REFERENCES TERRAIN_SURFACE_IMAGE(id);
ALTER TABLE TERRAIN_SURFACE_RECT ADD CONSTRAINT FK_TERRAIN_SURFACE_RECT_TERRAIN_SETTINGS FOREIGN KEY (dbTerrainSetting_id) REFERENCES TERRAIN_SETTINGS(id);

