INSERT INTO TERRAIN_SETTINGS VALUES (1, 100, 100, 100, 100, 'test1', TRUE);

INSERT INTO TERRAIN_IMAGE VALUES (1, 'image/jpeg', NULL, 1, 1);
INSERT INTO TERRAIN_IMAGE_TILE_SURFACE_TYPE VALUES (1, 1, 0, 0, 1);
INSERT INTO TERRAIN_IMAGE VALUES (2, 'image/jpeg', NULL, 1, 2);
INSERT INTO TERRAIN_IMAGE_TILE_SURFACE_TYPE VALUES (2, 1, 0, 0, 2);
INSERT INTO TERRAIN_IMAGE_TILE_SURFACE_TYPE VALUES (3, 1, 0, 1, 2);
INSERT INTO TERRAIN_IMAGE VALUES (3, 'image/jpeg', NULL, 2, 1);
INSERT INTO TERRAIN_IMAGE_TILE_SURFACE_TYPE VALUES (4, 1, 0, 0, 3);
INSERT INTO TERRAIN_IMAGE_TILE_SURFACE_TYPE VALUES (5, 1, 1, 0, 3);
INSERT INTO TERRAIN_IMAGE VALUES (4, 'image/jpeg', NULL, 2, 2);
INSERT INTO TERRAIN_IMAGE_TILE_SURFACE_TYPE VALUES (6, 1, 0, 0, 4);
INSERT INTO TERRAIN_IMAGE_TILE_SURFACE_TYPE VALUES (7, 1, 0, 1, 4);
INSERT INTO TERRAIN_IMAGE_TILE_SURFACE_TYPE VALUES (8, 1, 1, 0, 4);
INSERT INTO TERRAIN_IMAGE_TILE_SURFACE_TYPE VALUES (9, 1, 1, 1, 4);

INSERT INTO TERRAIN_SURFACE_IMAGE VALUES (1, 'image/jpeg', NULL, 2);
INSERT INTO TERRAIN_SURFACE_IMAGE VALUES (2, 'image/jpeg', NULL, 2);

INSERT INTO TERRAIN_SURFACE_RECT VALUES (1, 100, 100, 0, 0, 1, 1);

INSERT INTO TERRAIN_IMAGE_POSITION VALUES (1, 0, 0, 1, 1);

