/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*!40000 ALTER TABLE `FORUM_POST` DISABLE KEYS */;
/*!40000 ALTER TABLE `FORUM_THREAD` DISABLE KEYS */;
/*!40000 ALTER TABLE `FORUM_CATEGORY` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;


-- POST
ALTER TABLE `gamedb`.`FORUM_POST` CHANGE COLUMN `date` `postDate` DATETIME NOT NULL;
ALTER TABLE `gamedb`.`FORUM_POST` MODIFY COLUMN `content` VARCHAR(5000) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;
ALTER TABLE `gamedb`.`FORUM_POST` CHANGE COLUMN `title` `name` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;
ALTER TABLE `gamedb`.`FORUM_POST` ADD COLUMN `id2` INT(11) NOT NULL FIRST;
SET @i := 0;
UPDATE FORUM_POST SET id2 = (@i := (@i + 1));
ALTER TABLE `gamedb`.`FORUM_POST` DROP PRIMARY KEY,ADD PRIMARY KEY USING BTREE(`id2`);
ALTER TABLE `gamedb`.`FORUM_POST` DROP COLUMN `id`;
ALTER TABLE `gamedb`.`FORUM_POST` CHANGE COLUMN `id2` `id` INT(11) NOT NULL, DROP PRIMARY KEY,ADD PRIMARY KEY  USING BTREE(`id`);
ALTER TABLE `gamedb`.`FORUM_POST` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;
-- FORUM THREAD
ALTER TABLE `gamedb`.`FORUM_THREAD` DROP COLUMN `content`,
 CHANGE COLUMN `title` `name` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;
ALTER TABLE `gamedb`.`FORUM_THREAD` DROP COLUMN `viewCount`;
ALTER TABLE `gamedb`.`FORUM_POST` DROP INDEX `FKEC8AAD1E685BCC71`, DROP FOREIGN KEY `FKEC8AAD1E685BCC71`;
ALTER TABLE `gamedb`.`FORUM_THREAD` ADD COLUMN `id2` INT(11) NOT NULL FIRST;
SET @i := 0;
UPDATE FORUM_THREAD SET id2 = (@i := (@i + 1));
UPDATE FORUM_POST P SET P.forumThreadId = (SELECT T.id2 FROM FORUM_THREAD T WHERE P.forumThreadId = T.id);
ALTER TABLE `gamedb`.`FORUM_THREAD` DROP PRIMARY KEY,ADD PRIMARY KEY USING BTREE(`id2`);
ALTER TABLE `gamedb`.`FORUM_THREAD` DROP COLUMN `id`;
ALTER TABLE `gamedb`.`FORUM_THREAD` CHANGE COLUMN `id2` `id` INT(11) NOT NULL, DROP PRIMARY KEY,ADD PRIMARY KEY  USING BTREE(`id`);
ALTER TABLE `gamedb`.`FORUM_THREAD` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `gamedb`.`FORUM_POST` ADD INDEX `FKEC8AAD1E685BCC71`(`forumThreadId`),
 ADD CONSTRAINT `FKEC8AAD1E685BCC71` FOREIGN KEY `FKEC8AAD1E685BCC71` (`forumThreadId`)
    REFERENCES `FORUM_THREAD` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;
-- CATEGORY
ALTER TABLE `gamedb`.`FORUM_CATEGORY` DROP COLUMN `content`,
 CHANGE COLUMN `title` `name` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;
ALTER TABLE `gamedb`.`FORUM_THREAD` DROP INDEX `FKFB03F708422D8E77`, DROP FOREIGN KEY `FKFB03F708422D8E77`;
ALTER TABLE `gamedb`.`FORUM_CATEGORY` ADD COLUMN `id2` INT(11) NOT NULL FIRST;
SET @i := 0;
UPDATE FORUM_CATEGORY SET id2 = (@i := (@i + 1));
UPDATE FORUM_THREAD T SET T.categoryId = (SELECT C.id2 FROM FORUM_CATEGORY C WHERE T.categoryId = C.id);
ALTER TABLE `gamedb`.`FORUM_CATEGORY` DROP PRIMARY KEY,ADD PRIMARY KEY USING BTREE(`id2`);
ALTER TABLE `gamedb`.`FORUM_CATEGORY` DROP COLUMN `id`;
ALTER TABLE `gamedb`.`FORUM_CATEGORY` CHANGE COLUMN `id2` `id` INT(11) NOT NULL, DROP PRIMARY KEY,ADD PRIMARY KEY  USING BTREE(`id`);
ALTER TABLE `gamedb`.`FORUM_CATEGORY` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `gamedb`.`FORUM_THREAD` ADD INDEX `FKFB03F708422D8E77`(`categoryId`),
 ADD CONSTRAINT `FKFB03F708422D8E77` FOREIGN KEY `FKFB03F708422D8E77` (`categoryId`)
    REFERENCES `FORUM_CATEGORY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;
-- SUB FORUM
ALTER TABLE `gamedb`.`FORUM_SUB_FORUM` CHANGE COLUMN `title` `name` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;
ALTER TABLE `gamedb`.`FORUM_CATEGORY` DROP INDEX `FKF50F5A7C90A7A55D`, DROP FOREIGN KEY `FKF50F5A7C90A7A55D`;
ALTER TABLE `gamedb`.`FORUM_SUB_FORUM` ADD COLUMN `id2` INT(11) NOT NULL FIRST;
ALTER TABLE `gamedb`.`FORUM_SUB_FORUM` MODIFY COLUMN `content` VARCHAR(5000) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL;
SET @i := 0;
UPDATE FORUM_SUB_FORUM SET id2 = (@i := (@i + 1));
UPDATE FORUM_CATEGORY C SET C.subForumId = (SELECT S.id2 FROM FORUM_SUB_FORUM S WHERE C.subForumId = S.id);
ALTER TABLE `gamedb`.`FORUM_SUB_FORUM` DROP PRIMARY KEY,ADD PRIMARY KEY USING BTREE(`id2`);
ALTER TABLE `gamedb`.`FORUM_SUB_FORUM` DROP COLUMN `id`;
ALTER TABLE `gamedb`.`FORUM_SUB_FORUM` CHANGE COLUMN `id2` `id` INT(11) NOT NULL, DROP PRIMARY KEY,ADD PRIMARY KEY  USING BTREE(`id`);
ALTER TABLE `gamedb`.`FORUM_SUB_FORUM` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `gamedb`.`FORUM_CATEGORY` ADD INDEX `FKFB03F708422D8E77`(`subForumId`),
 ADD CONSTRAINT `FKF50F5A7C90A7A55D` FOREIGN KEY `FKF50F5A7C90A7A55D` (`subForumId`)
    REFERENCES `FORUM_SUB_FORUM` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;
SET foreign_key_checks=1;
/*!40000 ALTER TABLE `FORUM_POST` ENABLE KEYS */;
/*!40000 ALTER TABLE `FORUM_THREAD` ENABLE KEYS */;
/*!40000 ALTER TABLE `FORUM_CATEGORY` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;