SET SQL_SAFE_UPDATES=0;

ALTER TABLE TUTORIAL_TASK_CONFIG ADD `conditionConfig_id` int(11);
ALTER TABLE TUTORIAL_TASK_CONFIG ADD CONSTRAINT `FKD7E53DB40595EB0` FOREIGN KEY (`conditionConfig_id`) REFERENCES GUIDANCE_CONDITION_CONFIG (`id`);
ALTER TABLE TUTORIAL_TASK_CONFIG ADD INDEX `FKD7E53DB40595EB0` (`conditionConfig_id`);

UPDATE TUTORIAL_TASK_CONFIG T SET T.conditionConfig_id = (SELECT S.conditionConfig_id FROM TUTORIAL_STEP_CONFIG S WHERE T.id = S.dbTaskConfig);

ALTER TABLE TUTORIAL_TASK_CONFIG DROP COLUMN `taskText`;
DROP TABLE TUTORIAL_STEP_CONFIG;

SET SQL_SAFE_UPDATES=1;