SET SQL_SAFE_UPDATES=0;

DELETE FROM BACKUP_GENERIC_ITEM 
  WHERE base_id IN (SELECT base_id FROM BACKUP_USER_STATUS WHERE botConfig_id IS NOT NULL);
DELETE FROM BACKUP_BASE 
  WHERE id IN (SELECT base_id FROM BACKUP_USER_STATUS WHERE botConfig_id IS NOT NULL);
DELETE FROM BACKUP_USER_STATUS WHERE botConfig_id IS NOT NULL;

SET SQL_SAFE_UPDATES=1;