TRUNCATE BACKUP_USER_STATUS_LEVEL_TASK_DONE;
TRUNCATE BACKUP_GENERIC_ITEM;
UPDATE BACKUP_COMPARISON_VALUE SET parent_id = NULL;
TRUNCATE BACKUP_COMPARISON_VALUE;
TRUNCATE BACKUP_USER_STATUS;
TRUNCATE BACKUP_BASE;
TRUNCATE BACKUP_ENTRY;
