package com.btxtech.game.services.statistics.impl;

import com.btxtech.game.services.statistics.CurrentStatisticEntry;
import com.btxtech.game.services.statistics.StatisticsEntry;
import com.btxtech.game.services.utg.DbLevel;
import org.junit.Assert;
import org.junit.Test;

/**
 * User: beat
 * Date: 25.03.2012
 * Time: 16:09:23
 */
public class TestCurrentStatisticEntry {
    @Test
    public void CurrentStatisticEntry1() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(2);
        dbLevel.setXp(100);
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(2150, dbLevel, 15, "base1", "Planet1", (long) 100, 1, 10, new StatisticsEntry());
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(2150, currentStatisticEntry.getScore());
        Assert.assertEquals(15, currentStatisticEntry.getXp());
        Assert.assertEquals("base1", currentStatisticEntry.getUserName());
        Assert.assertEquals("Planet1", currentStatisticEntry.getPlanetName());
        Assert.assertEquals(100, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(1, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(10, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry2() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(3);
        dbLevel.setXp(15);
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(3999, dbLevel, 16, null,null, null, null, null, new StatisticsEntry());
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(3999, currentStatisticEntry.getScore());
        Assert.assertEquals(16, currentStatisticEntry.getXp());
        Assert.assertEquals(null, currentStatisticEntry.getUserName());
        Assert.assertEquals(null, currentStatisticEntry.getPlanetName());
        Assert.assertEquals(null, currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(null, currentStatisticEntry.getItemCount());
        Assert.assertEquals(null, currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry3() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2", "Planet2", (long) 1234, 12, 109, new StatisticsEntry());
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals("Planet2", currentStatisticEntry.getPlanetName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry4() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseKilledStructureBot();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2", "Planet1", (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals("Planet1", currentStatisticEntry.getPlanetName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(1, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(1, currentStatisticEntry.getKilled());
        Assert.assertEquals(1, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(1, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry5() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseKilledUnitsBot();
        statisticsEntry.increaseKilledUnitsBot();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2", "Planet2", (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals("Planet2", currentStatisticEntry.getPlanetName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(2, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(2, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(2, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(2, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry6() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseKilledStructurePlayer();
        statisticsEntry.increaseKilledStructurePlayer();
        statisticsEntry.increaseKilledStructurePlayer();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null, (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(3, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(3, currentStatisticEntry.getKilled());
        Assert.assertEquals(3, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(3, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry7() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseKilledUnitsPlayer();
        statisticsEntry.increaseKilledUnitsPlayer();
        statisticsEntry.increaseKilledUnitsPlayer();
        statisticsEntry.increaseKilledUnitsPlayer();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(4, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(4, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(4, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(4, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry8() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseKilledStructureBot();
        statisticsEntry.increaseKilledUnitsBot();
        statisticsEntry.increaseKilledUnitsBot();
        statisticsEntry.increaseKilledStructurePlayer();
        statisticsEntry.increaseKilledStructurePlayer();
        statisticsEntry.increaseKilledStructurePlayer();
        statisticsEntry.increaseKilledUnitsPlayer();
        statisticsEntry.increaseKilledUnitsPlayer();
        statisticsEntry.increaseKilledUnitsPlayer();
        statisticsEntry.increaseKilledUnitsPlayer();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(1, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(2, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(3, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(4, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(10, currentStatisticEntry.getKilled());
        Assert.assertEquals(4, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(6, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(3, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(7, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry9() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseLostStructureBot();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(1, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(1, currentStatisticEntry.getLost());
        Assert.assertEquals(1, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(1, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry10() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseLostUnitsBot();
        statisticsEntry.increaseLostUnitsBot();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(2, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(2, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(2, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(2, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry11() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseLostStructurePlayer();
        statisticsEntry.increaseLostStructurePlayer();
        statisticsEntry.increaseLostStructurePlayer();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(3, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(3, currentStatisticEntry.getLost());
        Assert.assertEquals(3, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(3, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry12() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseLostUnitsPlayer();
        statisticsEntry.increaseLostUnitsPlayer();
        statisticsEntry.increaseLostUnitsPlayer();
        statisticsEntry.increaseLostUnitsPlayer();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(4, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(4, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(4, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(4, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry13() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseLostUnitsPlayer();
        statisticsEntry.increaseLostUnitsBot();
        statisticsEntry.increaseLostUnitsBot();
        statisticsEntry.increaseLostStructureBot();
        statisticsEntry.increaseLostStructureBot();
        statisticsEntry.increaseLostStructureBot();
        statisticsEntry.increaseLostStructurePlayer();
        statisticsEntry.increaseLostStructurePlayer();
        statisticsEntry.increaseLostStructurePlayer();
        statisticsEntry.increaseLostStructurePlayer();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(3, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(2, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(4, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(1, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(10, currentStatisticEntry.getLost());
        Assert.assertEquals(7, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(3, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(5, currentStatisticEntry.getLostBot());
        Assert.assertEquals(5, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry14() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseBuiltStructures();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(1, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(1, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry15() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseBuiltUnits();
        statisticsEntry.increaseBuiltUnits();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(2, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(2, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry16() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseBuiltUnits();
        statisticsEntry.increaseBuiltUnits();
        statisticsEntry.increaseBuiltUnits();
        statisticsEntry.increaseBuiltStructures();
        statisticsEntry.increaseBuiltStructures();
        statisticsEntry.increaseBuiltStructures();
        statisticsEntry.increaseBuiltStructures();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(4, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(3, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(7, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry17() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseBasesDestroyedBot();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(1, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(1, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry18() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseBasesDestroyedPlayer();
        statisticsEntry.increaseBasesDestroyedPlayer();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(2, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(2, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry19() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseBasesDestroyedBot();
        statisticsEntry.increaseBasesDestroyedBot();
        statisticsEntry.increaseBasesDestroyedBot();
        statisticsEntry.increaseBasesDestroyedPlayer();
        statisticsEntry.increaseBasesDestroyedPlayer();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(3, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(2, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(5, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry20() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseBasesLostBot();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(1, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(1, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry21() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseBasesLostPlayer();
        statisticsEntry.increaseBasesLostPlayer();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(0, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(2, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(2, currentStatisticEntry.getBasesLost());
    }

    @Test
    public void CurrentStatisticEntry22() throws Exception {
        DbLevel dbLevel = new DbLevel();
        dbLevel.setNumber(9);
        dbLevel.setXp(123098);
        StatisticsEntry statisticsEntry = new StatisticsEntry();
        statisticsEntry.increaseBasesLostPlayer();
        statisticsEntry.increaseBasesLostPlayer();
        statisticsEntry.increaseBasesLostBot();
        statisticsEntry.increaseBasesLostBot();
        statisticsEntry.increaseBasesLostBot();
        CurrentStatisticEntry currentStatisticEntry = new CurrentStatisticEntry(9441, dbLevel, 54321, "base2",null , (long) 1234, 12, 109, statisticsEntry);
        Assert.assertEquals(dbLevel, currentStatisticEntry.getLevel());
        Assert.assertEquals(9441, currentStatisticEntry.getScore());
        Assert.assertEquals(54321, currentStatisticEntry.getXp());
        Assert.assertEquals("base2", currentStatisticEntry.getUserName());
        Assert.assertEquals(1234, (long) currentStatisticEntry.getBaseUpTime());
        Assert.assertEquals(12, (int) currentStatisticEntry.getItemCount());
        Assert.assertEquals(109, (int) currentStatisticEntry.getMoney());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getKilled());
        Assert.assertEquals(0, currentStatisticEntry.getKilledStructures());
        Assert.assertEquals(0, currentStatisticEntry.getKilledUnits());
        Assert.assertEquals(0, currentStatisticEntry.getKilledBot());
        Assert.assertEquals(0, currentStatisticEntry.getKilledPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructureBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructurePlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnitsPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getLost());
        Assert.assertEquals(0, currentStatisticEntry.getLostStructures());
        Assert.assertEquals(0, currentStatisticEntry.getLostUnits());
        Assert.assertEquals(0, currentStatisticEntry.getLostBot());
        Assert.assertEquals(0, currentStatisticEntry.getLostPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltStructures());
        Assert.assertEquals(0, currentStatisticEntry.getBuiltUnits());
        Assert.assertEquals(0, currentStatisticEntry.getBuilt());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedBot());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyedPlayer());
        Assert.assertEquals(0, currentStatisticEntry.getBasesDestroyed());
        Assert.assertEquals(3, currentStatisticEntry.getBasesLostBot());
        Assert.assertEquals(2, currentStatisticEntry.getBasesLostPlayer());
        Assert.assertEquals(5, currentStatisticEntry.getBasesLost());
    }
}
